/* This script contains every table created for this project.
   JLMFCompany's database is composed of 11 tables.*/

CREATE TABLE USER_ACCOUNT
(
    USER_NM VARCHAR(150) NOT NULL UNIQUE,
    FIRST_NAME VARCHAR(80) NOT NULL,
    LAST_NAME VARCHAR(150) NOT NULL,
    FIRST_LAST_NAME VARCHAR(230) NOT NULL,
    USR_ID VARCHAR(30) NOT NULL UNIQUE,
    USER_ADDRESS VARCHAR(400) NOT NULL,
    USER_CITY VARCHAR(100) NOT NULL,
    USER_STATE VARCHAR(100) NOT NULL,
    USER_COUNTRY VARCHAR(100) NOT NULL,
    USER_ZIP_CODE VARCHAR(10) NOT NULL,
    USER_EMAIL VARCHAR(200) NOT NULL UNIQUE,
    USER_BDAY DATE NOT NULL,
    USER_PHONE VARCHAR(100),
    USER_NATIONALITY VARCHAR(100) NOT NULL,
    USER_PASSPORT_NO VARCHAR(70) NOT NULL UNIQUE
)

CREATE TABLE USER_RECORDS
(
    ORDER_NO INT NOT NULL PRIMARY KEY,
    USR_ID VARCHAR(30) NOT NULL,
    TRANSACTION_DATE DATE NOT NULL,
    TRANSACTION_ID VARCHAR(120) NOT NULL UNIQUE,
    BOOKING_ID VARCHAR(30) NOT NULL UNIQUE
)

CREATE TABLE AIRBNB_BOOKING_DATA
(
    HOST_LOCATION_ID VARCHAR(30) NOT NULL UNIQUE,
    AIR_CONFIRMATION_ID VARCHAR(30) NOT NULL UNIQUE,
    TOTAL_GUESTS INT NOT NULL,
    HOST_ID_NO VARCHAR(30) NOT NULL,
    RATING_OVERALL DECIMAL(3,2) NOT NULL,
    BOOKING_ID VARCHAR(30) NOT NULL UNIQUE, 
)

CREATE TABLE AIRBNB_RESERVATION_DETAILS
(
    LISTING_NAME VARCHAR(230) NOT NULL,
    AIR_CONFIRMATION_ID VARCHAR(30) NOT NULL UNIQUE,
    HOST_NM VARCHAR(230) NOT NULL,
    GUEST_NAME VARCHAR(230) NOT NULL,
    GUEST_ADULT_NO INT NOT NULL,
    GUEST_CHILDREN_NO INT NOT NULL,
    GUEST_INFANT_NO INT NOT NULL,
    REASON_TO_VISIT VARCHAR(300) NOT NULL,
    START_DT DATE NOT NULL,
    END_DT DATE NOT NULL,
    HOST_LOCATION_ID VARCHAR(30) NOT NULL UNIQUE
)

CREATE TABLE BOOKINGS
(
    BOOKING_ID VARCHAR(30) NOT NULL UNIQUE,
    BOOKING_CLASS VARCHAR(7) NOT NULL
)

CREATE TABLE CARD_DETAILS
(
    NM VARCHAR(230) NOT NULL,
    CARD_COMPANY VARCHAR(100) NOT NULL,
    CARD_NO VARCHAR(21) NOT NULL UNIQUE,
    EXPIRY VARCHAR(5) NOT NULL,
    CVV VARCHAR(3) NOT NULL,
    USR_ID VARCHAR(30) NOT NULL,
    BILLING_ADDRESS VARCHAR(400) NOT NULL,
    BILLING_CITY VARCHAR(100) NOT NULL,
    BILLING_STATE VARCHAR(100) NOT NULL,
    BILLING_COUNTRY VARCHAR(100) NOT NULL,
    BILLING_ZIP_CODE VARCHAR(10) NOT NULL
)

CREATE TABLE EXPEDIA_PASSENGER_DATA
(
    PASSENGER_NAME VARCHAR(230) NOT NULL,
    BOOKING_ID VARCHAR(30) NOT NULL UNIQUE,
    EXP_E_TICKET_ID VARCHAR(80) NOT NULL UNIQUE,
    USER_NATIONALITY VARCHAR(100) NOT NULL,
    USER_PASSPORT_NO VARCHAR(70) NOT NULL UNIQUE,
    PASSENGER_2_NAME VARCHAR(230),
    EXP_E_TICKET_ID_2 VARCHAR(80) UNIQUE,
    PASSENGER_2_NATIONALITY VARCHAR(100),
    PASSPORT_NO_PASSENGER_2 VARCHAR(70) UNIQUE,
    PASSENGER_3_NAME VARCHAR(230),
    EXP_E_TICKET_ID_3 VARCHAR(80) UNIQUE,
    PASSENGER_3_NATIONALITY VARCHAR(100),
    PASSPORT_NO_PASSENGER_3 VARCHAR(70) UNIQUE,
    PASSENGER_4_NAME VARCHAR(230),
    EXP_E_TICKET_ID_4 VARCHAR(80) UNIQUE,
    PASSENGER_4_NATIONALITY VARCHAR(100),
    PASSPORT_NO_PASSENGER_4 VARCHAR(70) UNIQUE,
    PASSENGER_5_NAME VARCHAR(230),
    EXP_E_TICKET_ID_5 VARCHAR(80) UNIQUE,
    PASSENGER_5_NATIONALITY VARCHAR(100),
    PASSPORT_NO_PASSENGER_5 VARCHAR(70) UNIQUE,
    PASSENGER_2_NAME_M VARCHAR(230),
    EXP_E_TICKET_ID_2_M VARCHAR(80) UNIQUE,
    PASSENGER_2_M_NATIONALITY VARCHAR(100),
    PASSPORT_NO_PASSENGER_2_M VARCHAR(70) UNIQUE,
    PASSENGER_3_NAME_M VARCHAR(230),
    EXP_E_TICKET_ID_3_M VARCHAR(80) UNIQUE,
    PASSENGER_3_M_NATIONALITY VARCHAR(100),
    PASSPORT_NO_PASSENGER_3_M VARCHAR(70) UNIQUE,
    PASSENGER_4_NAME_M VARCHAR(230),
    EXP_E_TICKET_ID_4_M VARCHAR(80) UNIQUE,
    PASSENGER_4_M_NATIONALITY VARCHAR(100),
    PASSPORT_NO_PASSENGER_4_M VARCHAR(70) UNIQUE,
    PASSENGER_5_NAME_M VARCHAR(230),
    EXP_E_TICKET_ID_5_M VARCHAR(80) UNIQUE,
    PASSENGER_5_M_NATIONALITY VARCHAR(100),
    PASSPORT_NO_PASSENGER_5_M VARCHAR(70) UNIQUE,
    PASSENGER_2_NAME_I VARCHAR(230),
    EXP_E_TICKET_ID_2_I VARCHAR(80) UNIQUE,
    PASSENGER_2_I_NATIONALITY VARCHAR(100),
    PASSPORT_NO_PASSENGER_2_I VARCHAR(70) UNIQUE,
    PASSENGER_3_NAME_I VARCHAR(230),
    EXP_E_TICKET_ID_3_I VARCHAR(80) UNIQUE,
    PASSENGER_3_I_NATIONALITY VARCHAR(100),
    PASSPORT_NO_PASSENGER_3_I VARCHAR(70) UNIQUE,
    PASSENGER_4_NAME_I VARCHAR(230),
    EXP_E_TICKET_ID_4_I VARCHAR(80) UNIQUE,
    PASSENGER_4_I_NATIONALITY VARCHAR(100),
    PASSPORT_NO_PASSENGER_4_I VARCHAR(70) UNIQUE,
    PASSENGER_5_NAME_I VARCHAR(230),
    EXP_E_TICKET_ID_5_I VARCHAR(80) UNIQUE,
    PASSENGER_5_I_NATIONALITY VARCHAR(100),
    PASSPORT_NO_PASSENGER_5_I VARCHAR(70) UNIQUE
)

CREATE TABLE EXPEDIA_PASSENGER_TICKETS
(
    FLIGHT_CONFIRMATION_ID VARCHAR(15) NOT NULL UNIQUE,
    ALL_CATEGORIES_TICKET_ID VARCHAR(80) NOT NULL UNIQUE
)

CREATE TABLE EXPEDIA_TRIP_DETAILS
(
    ORIGIN VARCHAR(400) NOT NULL,
    DESTINATION VARCHAR(400) NOT NULL,
    FLIGHT_CONFIRMATION_ID VARCHAR(15) NOT NULL UNIQUE,
    DEPARTING_DATE DATE NOT NULL,
    RETURNING_DATE DATE,
    TICKET_CATEGORY VARCHAR(10) NOT NULL,
    DEPT_FLIGHT_TYPE VARCHAR(15) NOT NULL,
    DEPT_FIRST_FLIGHT_NO VARCHAR(15) NOT NULL,
    DEPT_SECOND_FLIGHT_NO VARCHAR(15),
    DEPT_THIRD_FLIGHT_NO VARCHAR(15),
    DEPT_TRIP_DURATION_HR DECIMAL(5,2) NOT NULL,
    RTRN_FLIGHT_TYPE VARCHAR(15) NOT NULL,
    RTRN_FIRST_FLIGHT_NO VARCHAR(15),
    RTRN_SECOND_FLIGHT_NO VARCHAR(15),
    RTRN_THIRD_FLIGHT_NO VARCHAR(15),
    RTRN_TRIP_DURATION_HR DECIMAL(5,2) NOT NULL
)

CREATE TABLE HOST_INFO
(
    HOST_ID_NO VARCHAR(30) NOT NULL UNIQUE,
    HOST_FIRST_NAME VARCHAR(80) NOT NULL,
    HOST_LAST_NAME VARCHAR(150) NOT NULL,
    HOST_NM VARCHAR(230) NOT NULL,
    LISTING_NAME VARCHAR(230) NOT NULL UNIQUE,
    LISTING_TYPE VARCHAR(80) NOT NULL,
    HOST_LOCATION_ID VARCHAR(30) NOT NULL UNIQUE,
    H_ADDRESS VARCHAR(400) NOT NULL UNIQUE,
    H_CITY VARCHAR(100) NOT NULL,
    H_STATE VARCHAR(100) NOT NULL,
    ZIP_CODE VARCHAR(10) NOT NULL,
    COUNTRY VARCHAR(100) NOT NULL
)

CREATE TABLE REVIEWS
(
    REVIEWER VARCHAR(230),
    RATING INT,
    AIR_CONFIRMATION_ID VARCHAR(30) NOT NULL UNIQUE
);

--END OF SCRIPT