/*Question 6: What is the sum of every flight passenger per flight confirmation id? */

SELECT 
    EPT.FLIGHT_CONFIRMATION_ID, 
    COUNT(EPT.FLIGHT_CONFIRMATION_ID) AS PASSENGER_COUNT 
FROM 
    EXPEDIA_PASSENGER_TICKETS EPT
GROUP BY EPT.FLIGHT_CONFIRMATION_ID

UNION ALL

SELECT 
    'SUM' FLIGHT_CONFIRMATION_ID, 
    COUNT(FLIGHT_CONFIRMATION_ID) 
FROM 
    EXPEDIA_PASSENGER_TICKETS
;


